site_name: ASDF Documentation
site_description: The ASDF Website
site_url: https://www.asdf-format.org
repo_url: https://github.com/asdf-format/asdf-website
repo_name: asdf-format/asdf-website
strict: true
use_directory_urls: false

docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - overview: overview.md
  - ASDF for FITS users: asdf_fits.md
  - specification: specification/index.md
  - extensions:
      - extensions/index.md
      - ASDF Transform Schemas: extensions/asdf-transform-schemas.md
      - ASDF Coordinates Schemas: extensions/asdf-coordinates-schemas.md
      - ASDF WCS Schemas: extensions/asdf-wcs-schemas.md
  - implementations:
      - implementations/index.md
      - Python: implementations/asdf-python.md
      - C: implementations/asdf-c.md
      - C++: implementations/asdf-cpp.md
      - Java: implementations/asdf-java.md
      - Julia: implementations/asdf-julia.md
  - tutorials: tutorials/index.md
  - community: community/index.md

theme:
  name: mkdocs
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  logo: assets/images/logo-light-mode.png

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

extra:
  external_refs:
    asdf-standard: https://www.asdf-format.org/projects/asdf-standard/en/latest/
    asdf: https://www.asdf-format.org/projects/asdf/en/stable/
    asdf-coordinates-schemas: https://www.asdf-format.org/projects/asdf-coordinates-schemas/en/latest/
    asdf-transform-schemas: https://www.asdf-format.org/projects/asdf-transform-schemas/en/latest/
    asdf-wcs-schemas: https://www.asdf-format.org/projects/asdf-wcs-schemas/en/latest/
    astropy: https://docs.astropy.org/en/stable/
    asdf-astropy: https://asdf-astropy.readthedocs.io/en/latest/

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
